FROM python:3
MAINTAINER Emil <emilbratt@mail.com>

ENV COCUVIDA_TESTING=true

RUN useradd -ms /bin/bash cocuvida
USER cocuvida
USER 1000:1000

# uvicorn will not be able to start from cli unless we add this to PATH
ENV PATH /home/cocuvida/.local/bin:${PATH}
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt
WORKDIR /OTGT/Energy_Management/cocuvida/app

CMD ["python", "-m", "cocuvida"]
