version: '3.9'

services:
  cocuvida_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocuvida_test
    hostname: cocuvida_test
    user: cocuvida
    command: 'python -u -m tests'
    environment:
      TZ: Europe/Oslo
    restart: 'no'
    volumes:
      - type: bind
        source: ../../
        target: /OTGT

  cocuvida_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocuvida_web
    hostname: cocuvida_web
    user: cocuvida
    command: 'uvicorn --lifespan on --port 8087 --host 0.0.0.0 --reload cocuvida.web:app'
    environment:
      TZ: Europe/Oslo
    restart: unless-stopped
    ports:
      - 8087:8087
    volumes:
      - type: bind
        source: ../../
        target: /OTGT

  cocuvida_controlplans:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocuvida_controlplans
    hostname: cocuvida_controlplans
    user: cocuvida
    command: 'python -u -m cocuvida controlplans'
    environment:
      TZ: Europe/Oslo
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../../
        target: /OTGT

  cocuvida_prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocuvida_prod
    hostname: cocuvida_prod
    user: cocuvida
    environment:
      TZ: Europe/Oslo
    restart: unless-stopped
    ports:
      - 8087:8087
    volumes:
      - type: bind
        source: ../../
        target: /OTGT
