-- DOWNLOADED ELSPOT DATA FROM NORDPOOL
CREATE TABLE IF NOT EXISTS elspot_raw (
  elspot_date TEXT NOT NULL PRIMARY KEY,
  elspot_data JSON NOT NULL
);

-- CONTROL-PLANS FOR AUTO-SETTING THE STATE OF SPECIFIED BINARY SWITCHES (ON/OFF)
CREATE TABLE IF NOT EXISTS switch_control_plans (
  plan_name     TEXT NOT NULL PRIMARY KEY,
  plan_data     JSON NOT NULL,
  created_date  DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE (plan_data)
);
