version: '3'

services:
  cocuvida_prod:
    init: true
    build:
      context: ./cocuvida
      dockerfile: Dockerfile
    container_name: cocuvida_prod
    hostname: cocuvida_prod
    user: cocuvida
    command: 'python -u -m cocuvida'
    environment:
      TZ: Europe/Oslo
    restart: 'no'
    ports:
      - 8087:8087
    volumes:
      - type: bind
        source: ../
        target: /OTGT

  homeassistant_prod:
    container_name: homeassistant_prod
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: Europe/Oslo
    volumes:
      - ./homeassistant/bindmount/config:/config
    restart: unless-stopped
    privileged: false
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  # https://github.com/eclipse/mosquitto/tree/master/docker/generic
  mosquitto_prod:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mosquitto_prod
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ./mosquitto/bindmount:/mosquitto

  # # https://github.com/Koenkk/zigbee2mqtt/tree/master/docker
  # # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  # # https://www.zigbee2mqtt.io/guide/installation/02_docker.html
  zigbee2mqtt_prod:
    container_name: zigbee2mqtt_prod
    restart: unless-stopped
    build:
      context: ./zigbee2mqtt
      dockerfile: Dockerfile
    volumes:
      - ./zigbee2mqtt/bindmount:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8088:8088
    environment:
      TZ: Europe/Oslo
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
