version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"

    # HOST NETWORK MODE
    network_mode: host

    # LOCALE
    environment:
      TZ: Europe/Oslo

    # CONFIG FILES
    volumes:
      - /etc/homeassistant/config:/config

    # RESTART POLICY
    restart: unless-stopped

    # MIGHT BE NEEDED FOR HA TO PLAY NICELY WITH SOME USB DEVICES ETC.
    privileged: false

    # MAP USB DEVICE - IF FOR EXAMPLE YOU WANNA USE WITH A CONBEE II USB-STICK..
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
