version: '3'

services:
  fetch_elspot:
    build: ./fetch_elspot
    container_name: fetch_elspot
    user: "elprice"
    environment:
      NORDPOOL_API_PAGE: '10' # currently in use
      NORDPOOL_CURRENCY: 'NOK' # EUR, NOK, SEK, ..
      NORDPOOL_UNIT: 'NOK/MWh'
      NORDPOOL_RESHAPE_UNIT: 'ore/kWh' # 'NOK/kW', 'ore/kWh' e.g.
      NORDPOOL_FETCH_HOUR: '13' # wait until this hour to try fetching
      NORDPOOL_FETCH_MINUTE: '15' # wait until this minute
      WEB_DATASTORE_API_VERSION: '0' # we might change  api in the future
      WEB_DATASTORE_URL: 'web_datastore:8085' # to web_datastore
      TZ: Europe/Oslo
    restart: unless-stopped
    volumes:
      - ./fetch_elspot/app:/app
    restart: unless-stopped

  web_datastore:
    container_name: web_datastore
    build: ./web_datastore
    environment:
      TZ: Europe/Oslo
      WEB_PORT: '8085'
      HOST_ALLOW_UPLOAD_ELSPOT: 'fetch_elspot'
      HOST_ALLOW_UPLOAD_PLOT: 'generate_plot'
      HOST_ALLOW_UPLOAD_SENSOR: 'generate_sensor'
    volumes:
      - ./web_datastore/app:/app
      # - ./bindmount:/data
    ports:
      - "8085:8085"
    restart: unless-stopped

  # generate_plot:
  #   container_name: generate_plot
  #   build: ./generate_plot
  #   environment:
  #     TZ: Europe/Oslo
  #   volumes:
  #     - ./generate_plot/app:/app
  #   restart: unless-stopped

  # generate_sensor:
  #   container_name: generate_sensor
  #   build: ./generate_sensor
  #   environment:
  #     TZ: Europe/Oslo
  #   volumes:
  #     - ./generate_sensor/app:/app
  #   restart: unless-stopped

  # mqtt_client:
  #   container_name: mqtt_client
  #   build: ./mqtt_client
  #   environment:
  #     TZ: Europe/Oslo
  #   user: 1000:1000
  #   environment:
  #     UID: 1000
  #     GID: 1000
  #   restart: unless-stopped
