version: '3'

services:
  fetch_elspot:
    build: ./fetch_elspot
    container_name: fetch_elspot
    user: "elprice"
    hostname: fetch_elspot
    environment:
      TZ: Europe/Oslo
      NORDPOOLDAYAHEAD_API_VERSION: '1'
      NORDPOOL_CURRENCY: 'NOK' # EUR, NOK, SEK, ..
      NORDPOOL_UNIT: 'NOK/MWh'
      NORDPOOL_RESHAPE_UNIT: 'ore/kWh' # 'NOK/kW', 'ore/kWh' e.g.
      NORDPOOL_FETCH_HOUR: '13' # wait until this hour to try fetching
      NORDPOOL_FETCH_MINUTE: '15' # wait until this minute
      HTTPDATASTORE_API_VERSION: '1'
      WEB_DATASTORE_URL: 'http://web_datastore:8085' # to web_datastore
    restart: unless-stopped
    volumes:
      - ../../:/OTGT
    restart: unless-stopped

  web_datastore:
    container_name: web_datastore
    build: ./web_datastore
    environment:
      TZ: Europe/Oslo
      DATABASE_FILE: '/OTGT/Energy_Management/elprice/web_datastore/data.sqlite' # "data.sqlite" should be in gitignore list
      WEB_PORT: '8085'
      MQTT_PUBLISH_API_VERSION: '0'
      ENVIRONMENT_INI_FILE: '/OTGT/environment.ini'
      MQTT_CLIENT_ID: 'elprice_web_datastore'
      MQTT_TOPIC_ELPRICE_ELSPOT_RESHAPED: 'elprice/elspot/reshaped'
    volumes:
      - ../../:/OTGT
    ports:
      - "8085:8085"
    restart: unless-stopped

  generate_plot:
    container_name: generate_plot
    build: ./generate_plot
    environment:
      TZ: Europe/Oslo
      CONFIG_FILE: '/OTGT/environment.ini'
      HTTPDATASTORE_API_VERSION: '0'
      PLOT_GENERATOR_API_VERSION: '0'
      PLOT_Y_TICK_START: '0'
      PLOT_Y_TICK_END: '800'
      PLOT_Y_TICK_STEP: '50'
      WEB_DATASTORE_URL: 'http://web_datastore:8085'
      ENVIRONMENT_INI_FILE: '/OTGT/environment.ini'
      MQTT_CLIENT_ID: 'elprice_generate_plot'
      MQTT_TOPIC_ELPRICE_ELSPOT_RESHAPED: 'elprice/elspot/reshaped'
    volumes:
      - ../../:/OTGT
    restart: unless-stopped

  generate_states:
    container_name: generate_states
    build: ./generate_states
    environment:
      TZ: Europe/Oslo
      HTTPDATASTORE_API_VERSION: '0'
      STATE_GENERATOR_API_VERSION: '0'
      WEB_DATASTORE_URL: 'http://web_datastore:8085'
      ENVIRONMENT_INI_FILE: '/OTGT/environment.ini'
      MQTT_CLIENT_ID: 'elprice_generate_states'
      MQTT_TOPIC_ELPRICE_ELSPOT_RESHAPED: 'elprice/elspot/reshaped'
    volumes:
      - ../../:/OTGT
    restart: unless-stopped

  mqtt_distribute:
    container_name: mqtt_distribute
    build: ./mqtt_distribute
    environment:
      TZ: Europe/Oslo
      WEB_DATASTORE_URL: 'http://web_datastore:8085' # to web_datastore
      ENVIRONMENT_INI_FILE: '/OTGT/environment.ini'
      MQTT_CLIENT_ID: 'elprice_mqtt_distribute'
      MQTT_TOPIC_ELPRICE_ELSPOT_RESHAPED: 'elprice/elspot/reshaped'
    volumes:
      - ../../:/OTGT
    restart: unless-stopped
