version: '3'

# NOTE: for use inside this repo do not run this file directly, run setup.sh !!
services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto
    user: 1000:1000
    environment:
      UID: 1000
      GID: 1000
    restart: unless-stopped
    volumes:
      - ./bindmount:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
