version: '3'

# NOTE: for use inside this repo do not run this file directly, run setup.sh !!
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: 1000:1000
    environment:
      UID: 1000
      GID: 1000

    # restart policy
    restart: unless-stopped

    # bind mounts
    volumes:
      - ./bindmount/config:/mosquitto/config
      - ./bindmount/data:/mosquitto/data
      - ./bindmount/log:/mosquitto/log

    network_mode: host

    # ports:
    #   - 1883:1883
    #   - 9001:9001
