version: "3.9"

# db_datawarehouse uses a docker volume for persistent database store
# web_cip_info uses a docker wolume for user files (object storage)
# no volumes set up for db_retail, yet

services:
  db_retail:
    build: ./db_retail
    container_name: db_retail
    environment:
      MSSQL_SA_PASSWORD: Mys3cretPWD
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  db_datawarehouse:
    build: ./db_datawarehouse
    container_name: db_datawarehouse
    volumes:
      - db_datawarehouse:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_DATABASE: CIP
      MARIADB_USER: cippost
      MARIADB_PASSWORD: mypassword
    ports:
      - "3306:3306"

  web_barcode_generator:
    build: ./barcode_generator
    container_name: web_barcode_generator
    volumes:
      - ../../:/code/app
    ports:
      - "8081:8081"
    restart: always

  web_cip_info:
    depends_on:
      - db_datawarehouse
      - db_retail
      - web_barcode_generator
    build: ./web_cip_info
    container_name: web_cip_info
    volumes:
      - web_cip_info:/cip_info_assets
      - ../../:/var/www/html
      # - ./web_cip_info/freetds/freetds.conf:/etc/freetds/freetds.conf
      # - ./web_cip_info/freetds/odbc.ini:/etc/odbc.ini
      # - ./web_cip_info/freetds/odbcinst.ini:/etc/odbcinst.ini
      - ./web_cip_info/php_conf/php.ini_developement:/usr/local/etc/php/php.ini
      - ./web_cip_info/apache-conf/apache2.conf:/etc/apache2/apache2.conf
      - ./web_cip_info/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./web_cip_info/conf-available/docker-php.conf:/etc/apache2/conf-available/docker-php.conf
    ports:
      - "8080:80"
    restart: always

volumes:
  db_datawarehouse: {}
  web_cip_info: {}
