version: "3.9"

# db_datawarehouse uses a docker volume for persistent database store
# web_cip_info uses a docker wolume for user files (object storage)

services:
  db_datawarehouse:
    build: ./db_datawarehouse
    container_name: db_datawarehouse
    volumes:
      - db_datawarehouse:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_DATABASE: CIP
      MARIADB_USER: cippost
      MARIADB_PASSWORD: mypassword
    ports:
      - "3306:3306"

  web_barcode_generator:
    build: ./barcode_generator
    container_name: web_barcode_generator
    volumes:
      - ../../:/code/app
    ports:
      - "8081:8081"
    restart: always

  web_cip_info:
    depends_on:
      - db_datawarehouse
      - web_barcode_generator
    build: ./cip_info
    container_name: web_cip_info
    volumes:
      - web_cip_info:/cip_info_assets
      - ../../:/var/www/html
      - ./cip_info/php_conf/php.ini_developement:/usr/local/etc/php/php.ini
      - ./cip_info/apache-conf/apache2.conf:/etc/apache2/apache2.conf
      - ./cip_info/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./cip_info/conf-available/docker-php.conf:/etc/apache2/conf-available/docker-php.conf
    ports:
      - "8080:80"
    restart: always

volumes:
  db_datawarehouse: {}
  web_cip_info: {}
